"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class calib_t(object):
    __slots__ = ["utime", "K_cam_left", "K_cam_right", "cam_left_imu", "cam_right_imu", "cam_left_velo", "cam_right_velo", "velo_imu"]

    def __init__(self):
        self.utime = 0
        self.K_cam_left = [ 0.0 for dim0 in range(9) ]
        self.K_cam_right = [ 0.0 for dim0 in range(9) ]
        self.cam_left_imu = [ 0.0 for dim0 in range(16) ]
        self.cam_right_imu = [ 0.0 for dim0 in range(16) ]
        self.cam_left_velo = [ 0.0 for dim0 in range(16) ]
        self.cam_right_velo = [ 0.0 for dim0 in range(16) ]
        self.velo_imu = [ 0.0 for dim0 in range(16) ]

    def encode(self):
        buf = BytesIO()
        buf.write(calib_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">q", self.utime))
        buf.write(struct.pack('>9d', *self.K_cam_left[:9]))
        buf.write(struct.pack('>9d', *self.K_cam_right[:9]))
        buf.write(struct.pack('>16d', *self.cam_left_imu[:16]))
        buf.write(struct.pack('>16d', *self.cam_right_imu[:16]))
        buf.write(struct.pack('>16d', *self.cam_left_velo[:16]))
        buf.write(struct.pack('>16d', *self.cam_right_velo[:16]))
        buf.write(struct.pack('>16d', *self.velo_imu[:16]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != calib_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return calib_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = calib_t()
        self.utime = struct.unpack(">q", buf.read(8))[0]
        self.K_cam_left = struct.unpack('>9d', buf.read(72))
        self.K_cam_right = struct.unpack('>9d', buf.read(72))
        self.cam_left_imu = struct.unpack('>16d', buf.read(128))
        self.cam_right_imu = struct.unpack('>16d', buf.read(128))
        self.cam_left_velo = struct.unpack('>16d', buf.read(128))
        self.cam_right_velo = struct.unpack('>16d', buf.read(128))
        self.velo_imu = struct.unpack('>16d', buf.read(128))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if calib_t in parents: return 0
        tmphash = (0x5e7dc41bd07f3723) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if calib_t._packed_fingerprint is None:
            calib_t._packed_fingerprint = struct.pack(">Q", calib_t._get_hash_recursive([]))
        return calib_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

