"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class pointcloud_t(object):
    __slots__ = ["utime", "size", "points"]

    def __init__(self):
        self.utime = 0
        self.size = 0
        self.points = []

    def encode(self):
        buf = BytesIO()
        buf.write(pointcloud_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        buf.write(struct.pack(">qi", self.utime, self.size))
        for i0 in range(self.size):
            buf.write(struct.pack('>4f', *self.points[i0][:4]))

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != pointcloud_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return pointcloud_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = pointcloud_t()
        self.utime, self.size = struct.unpack(">qi", buf.read(12))
        self.points = []
        for i0 in range(self.size):
            self.points.append(struct.unpack('>4f', buf.read(16)))
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if pointcloud_t in parents: return 0
        tmphash = (0x668519cd924558) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if pointcloud_t._packed_fingerprint is None:
            pointcloud_t._packed_fingerprint = struct.pack(">Q", pointcloud_t._get_hash_recursive([]))
        return pointcloud_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

