"""LCM type definitions
This file automatically generated by lcm.
DO NOT MODIFY BY HAND!!!!
"""

try:
    import cStringIO.StringIO as BytesIO
except ImportError:
    from io import BytesIO
import struct

class tracked_object_type_t(object):
    __slots__ = []

    car = 0
    van = 1
    truck = 2
    pedestrian = 3
    person = 4
    cyclist = 5
    tram = 6
    misc = 7
    num_classes = 8

    def __init__(self):
        pass

    def encode(self):
        buf = BytesIO()
        buf.write(tracked_object_type_t._get_packed_fingerprint())
        self._encode_one(buf)
        return buf.getvalue()

    def _encode_one(self, buf):
        pass

    def decode(data):
        if hasattr(data, 'read'):
            buf = data
        else:
            buf = BytesIO(data)
        if buf.read(8) != tracked_object_type_t._get_packed_fingerprint():
            raise ValueError("Decode error")
        return tracked_object_type_t._decode_one(buf)
    decode = staticmethod(decode)

    def _decode_one(buf):
        self = tracked_object_type_t()
        return self
    _decode_one = staticmethod(_decode_one)

    _hash = None
    def _get_hash_recursive(parents):
        if tracked_object_type_t in parents: return 0
        tmphash = (0x12345678) & 0xffffffffffffffff
        tmphash  = (((tmphash<<1)&0xffffffffffffffff)  + (tmphash>>63)) & 0xffffffffffffffff
        return tmphash
    _get_hash_recursive = staticmethod(_get_hash_recursive)
    _packed_fingerprint = None

    def _get_packed_fingerprint():
        if tracked_object_type_t._packed_fingerprint is None:
            tracked_object_type_t._packed_fingerprint = struct.pack(">Q", tracked_object_type_t._get_hash_recursive([]))
        return tracked_object_type_t._packed_fingerprint
    _get_packed_fingerprint = staticmethod(_get_packed_fingerprint)

